### ISSUE TITLE
423549 - Client didn't receive email

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1131] opened 2016-05-03 20:04 UTC
![image](https://cloud.githubusercontent.com/assets/8440903/14996555/8cd5b218-1148-11e6-8716-282ae1b9a62e.png)

**Comment by bradatkins** [comment] 2016-05-04 01:04
I believe this was reported already, and was told that we (206 Tours) received it (as the CC)

And since we received it OK, it's not a DB thing unfortunately

**Comment by bradatkins** [comment] 2016-05-04 01:07
Duplicate of #1128 so I'll close this one

**Closed by bradatkins** 2016-05-04 01:07 UTC
