### ISSUE TITLE
Making a payment on a CAD acct after registering

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#563] opened 2015-08-27 13:28 UTC
This is where i keep getting confused and why i think this may be a problem for people in the office.

I registered myself 420440 and when i registered and made a $1.00 payment, my cc charge went in to the new MC acct. as $1.00 CAD. 

I just went back to my booking, made a $1.00 payment by AX, and it posted in to the old account as $0.68.  Since the DB doesn't know if a CC or an address is foreign, how are we supposed to clearly make any future payments on bookings?  If everything after the initial payment gets processed as USD, the clients invoice math wise will always be off a little right?

![image](https://cloud.githubusercontent.com/assets/8440903/9521568/9ae1d10e-4c9d-11e5-8d08-e30095a99ab1.png)

**Comment by bradatkins** [comment] 2015-08-27 13:43
An order must be paid for completely in the original currency it was placed
in.

Keep in mind, most people don't bounce around paying different currencies.

When you said you went and made a payment to the booking, did you do that
as a Customer or Admin? The DB should be forcing it to be CAD, and thus
rejecting your AX.

Brad

**Comment by ali206** [comment] 2015-08-27 13:45
I agree that it should be paid for in original currency but that's where the problem is. 

I made the payment as Admin - AX was not rejected and currency was USD. 

Everyone else in the office can and will be making payments as users, not as the client.  We don't login as the client to make payments.

**Comment by bradatkins** [comment] 2015-08-27 14:03
OK I will make sure in the Admin it forces the original currency of the
order.

**Comment by ali206** [comment] 2015-08-27 14:13
Ok. 

Also i just logged in as the "client" to my order and when you view the invoice from there the math is wrong, i'm not sure where the #'s are coming from.  Is it updating based in the current exchange rate (which it shouldn't be)?

Logged in as the client i was able to make another $1.00 pmnt with my AX (last image) 

![image](https://cloud.githubusercontent.com/assets/8440903/9522602/9def9678-4ca3-11e5-8ca8-448c31f06bc1.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9522610/a47dde82-4ca3-11e5-9899-edd473e9f882.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9522617/ac0ae7da-4ca3-11e5-9822-04eeea66e8c5.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9522653/cfe083e0-4ca3-11e5-9021-ed973eb5059f.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9522673/e4131c7e-4ca3-11e5-93cc-06d60c2bb88d.png)

![image](https://cloud.githubusercontent.com/assets/8440903/9522725/28fa9e52-4ca4-11e5-955a-5fbb0d61c8e5.png)

**Comment by bradatkins** [comment] 2015-08-27 14:22
Checking...

**Comment by bradatkins** [comment] 2015-08-27 14:39
I've added the message, in red:

![image](https://cloud.githubusercontent.com/assets/8440255/9523402/d59c65de-4ca7-11e5-85d5-510f610da416.png)

I've tested it rejects anything non- Mastercard/Visa:

![image](https://cloud.githubusercontent.com/assets/8440255/9523413/e1508c16-4ca7-11e5-9d01-0ef5393dff5b.png)

And it is forcing CAD

![image](https://cloud.githubusercontent.com/assets/8440255/9523425/e7dc1eec-4ca7-11e5-98b0-7e571f0cc9aa.png)

All from the client side.

**Comment by bradatkins** [comment] 2015-08-27 14:40
![image](https://cloud.githubusercontent.com/assets/8440255/9523454/1664f0ae-4ca8-11e5-8a2c-9d88b2d595f7.png)

**Comment by bradatkins** [comment] 2015-08-27 14:54
I just did some changes to the admin to force the currency:

![image](https://cloud.githubusercontent.com/assets/8440255/9523874/026bd7aa-4caa-11e5-8581-d28e1f72c890.png)

![image](https://cloud.githubusercontent.com/assets/8440255/9523877/064aae1e-4caa-11e5-8500-70c17b4050cf.png)

**Comment by bradatkins** [comment] 2015-08-27 15:02
I took a few screen shots to ensure the numbers are lining up. They all line up, except the current price of the tour, but that is because of currency fluctuation.

Let me know if you find any other issues. If possible, please post them in seperate Git issues.

Thanks!

![image](https://cloud.githubusercontent.com/assets/8440255/9524086/098bf3a2-4cab-11e5-8cf0-c0f59e6cc6f8.png)

**Comment by ali206** [comment] 2015-08-27 15:05
Ok before i take a look at everything again just one question...I thought the currency was not supposed to fluctuate?  I thought when the person registered that is the exch. rate they were locked in to so that their tour price is not constantly changing (which would be confusing)

**Comment by bradatkins** [comment] 2015-08-27 15:08
Man I hate email.
The currency will not fluctuate on their order.

It will fluctuate daily for the website (eg people who haven't placed an order)

**Comment by ali206** [comment] 2015-08-31 17:16
Ok should we close this now since we most likely have to change the way we were doing things?

**Comment by bradatkins** [comment] 2015-08-31 18:41
I think we should close it cause the issue is resolved. How things get done will generally be the same.

**Closed** 2015-09-11 16:51 UTC
Labels: For Review by 206 Tours Staff
