### ISSUE TITLE
Incomplete Orders

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#138] opened 2015-01-02 15:47 UTC
Hi Brad, 

Can you add a button that allows us to delete incomplete orders?  There are a bunch of test orders that are incomplete but we have no way of removing them from the list. 

![image](https://cloud.githubusercontent.com/assets/8440903/5597232/b3369442-926c-11e4-97e4-fe2653dc8adc.png)

**Comment by bradatkins** [comment] 2015-09-12 13:18
Duplicate of #265

**Closed by bradatkins** 2015-09-12 13:18 UTC
Labels: enhancement
