### ISSUE TITLE
DB | Incorrect Payment Amount | Tour JH090117 (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1450] opened 2016-08-30 16:53 UTC
767e77f176160e153c748e542e6650b8

![image](https://cloud.githubusercontent.com/assets/10079829/18098560/c124e596-6eb0-11e6-9d90-8d4e1a73a86f.png)

**Comment by bradatkins** [comment] 2016-09-25 13:13
Duplicate of one I just commented on, closing

**Closed by bradatkins** 2016-09-25 13:13 UTC
