### ISSUE TITLE
RevisedOrder@206tours.com for ALL updates

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#305] opened 2015-03-30 19:57 UTC
Hi Brad, 

Can you have ALL updates (passport, address, flight info, insurance, change from air + land to L/O, added pax, diff. dept city or return city, etc) that either clients or employees in office do, be sent to revisedorders@206tours.com? 

Milanka is going to create that address.  It will be easier to keep track of all changes this way.

**Comment by bradatkins** [comment] 2015-03-30 20:23
Curious as to why we are doing this? Doesn't the DB already track this?

**Comment by ali206** [comment] 2015-03-30 20:37
you mean doesn't the DB track this in the order audit report?  Yes but that doesn't inform people at the time it's done.

We need to do this b/c if a client or someone in the office updates an invoice that is registered for Tour#206, and there is no email about it, Rinda will have no idea that anything changed on the invoice.

**Comment by bradatkins** [comment] 2015-03-30 22:55
Say she gets this email, what is she going to do with it? I just see this email inbox becoming an un-usable mess.

I'm sure there's a better way...

**Comment by ali206** [comment] 2015-03-31 13:32
When she gets that email, let's say it's a name correction - she then has to go in to Amadeus and correct the person's name so that an incorrect ticket is not issued.  If she doesn't get an email then she may not catch that.  It's the same way as the DB is letting me know when someone changes a person's tour so that i can keep track of correct trip information for insurance purposes.

**Comment by bradatkins** [comment] 2015-03-31 13:36
OK. That makes sense :)

**Comment by ali206** [comment] 2015-04-07 18:09
Milanka created this email address by the way so if you could implement this ASAP that would be great :)

**Comment by bradatkins** [comment] 2015-05-28 01:59
a) send to only revisedorders@206tours.com.
b) send to revisedorders@206tours.com. and CC the Account Manager
c) sent just to the Account Manager (if there is none, send to revisedorders@206tours.com.)

Sandra says option C

**Comment by bradatkins** [comment] 2015-05-28 13:48
Bcc accounting too

**Comment by ali206** [comment] 2015-05-28 13:49
No leave as all being sent to orders@206tours.com now that account managers will be copied in to the emails and only change the subject of the email as per Sandy's example.

**Comment by bradatkins** [comment] 2015-05-30 18:11
I have completed this modification. I will be monitoring it to make sure I've captured all the areas.

The DB will send the email out if the customer or someone in the office changes the information.

I hope this doesn't generate an overload of email traffic for the folks.

The DB sends the email to revisedorder@206tours.com and the Tour Manager (or rok)


Here's an example:

![image](https://cloud.githubusercontent.com/assets/8440255/7898685/cac8d286-06d5-11e5-923c-6fd6133f1ec0.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7898689/cef86588-06d5-11e5-890f-aee94dfd23e3.png)

**Comment by ali206** [comment] 2015-08-03 16:06
Can you adjust this to also email out if the insurance premium has changed?

**Comment by bradatkins** [comment] 2015-09-12 13:01
This will be done as part of #585 if Milanka approves

**Comment by bradatkins** [comment] 2015-09-12 13:20
Duplicate of #585

**Closed by bradatkins** 2015-09-12 13:20 UTC
Labels: enhancement, For Review by 206 Tours Staff
