### ISSUE TITLE
???? weird email again

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#369] opened 2015-05-12 13:29 UTC
![image](https://cloud.githubusercontent.com/assets/8440903/7588159/42466810-f889-11e4-9229-e3c7406b73d7.png)

![image](https://cloud.githubusercontent.com/assets/8440903/7588162/47f711f6-f889-11e4-86ac-0561b7d816c8.png)

There are no payments from yesterday for $1,288 that were CC's

**Comment by ali206** [comment] 2015-05-19 17:22
same tour not sure what the booking # is though:

![image](https://cloud.githubusercontent.com/assets/8440903/7709305/19a27aba-fe2a-11e4-8c04-5541776c891c.png)

**Comment by bradatkins** [comment] 2015-05-19 17:35
Interesting:

[image: Inline image 1]

**Comment by ali206** [comment] 2015-05-19 18:15
yeah and on DC032816 this client just received this email and no payment was actually made
![image](https://cloud.githubusercontent.com/assets/8440903/7710385/86e02fc6-fe31-11e4-926f-40135e6846ac.png)

**Comment by bradatkins** [comment] 2015-05-19 18:27
Did she make the payment herself, or did you?

**Comment by ali206** [comment] 2015-05-19 18:29
DB says customer but i'm not positive that's accurate and it was done via paypal - we got the email for the payment but it's pending as a check in the DB

**Comment by bradatkins** [comment] 2015-09-04 01:50
Duplicate of #383

**Closed by bradatkins** 2015-09-04 01:50 UTC
