### ISSUE TITLE
Creating more then 1 tracking # per order

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#250] opened 2015-03-10 19:40 UTC
#6. We need the ability to be able to create more than 1 tracking # on the same order

**Comment by chris206** [comment] 2017-01-13 21:02
Tracking numbers need to be autogenerated for all subordinate addresses on order
![image](https://cloud.githubusercontent.com/assets/22382144/21945507/9c825732-d9a9-11e6-89de-f1f0a3633214.png)

**Comment by bradatkins** [comment] 2017-01-28 02:12
Duplicate of #1807

**Closed by bradatkins** 2017-01-28 02:12 UTC
Labels: enhancement, For Review by 206 Tours Staff
