### ISSUE TITLE
DB | Incorrect Payment amount  | Tour ML092516 (Liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1396] opened 2016-08-12 13:57 UTC
d0be18119b90503a431d7326a52b29d3

![image](https://cloud.githubusercontent.com/assets/10079829/17624566/188929ba-6073-11e6-8788-4d9de89b6ed9.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17624573/2064fe98-6073-11e6-81ad-2b3d0bd6ee09.png)

**Comment by bradatkins** [comment] 2016-09-25 13:14
Duplicate of the one I just commented on, closing

**Closed by bradatkins** 2016-09-25 13:14 UTC
