### ISSUE TITLE
423421 - got a blank ACH email after Irena transferred payments???

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1089] opened 2016-04-20 16:18 UTC
![image](https://cloud.githubusercontent.com/assets/8440903/14682080/ee04c972-06f1-11e6-9bec-7845cfa26b98.png)

**Comment by bradatkins** [comment] 2016-04-21 00:40
Probably duplicate of #1092

**Closed by bradatkins** 2016-04-21 00:40 UTC
