### ISSUE TITLE
applying a lump sum cc payment in DB - no transaction ID only section

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1008] opened 2016-04-04 14:20 UTC
Is there anyway to have the ability to just apply the transaction ID when splitting up large CC payments that were already charged?

Currently there is no option and we don't want to re-charge the cc (which is the only option at the moment)

![image](https://cloud.githubusercontent.com/assets/8440903/14250951/a7a6f086-fa4e-11e5-8e96-e863c3aaab1c.png)

Also can you please fix Irena's issues for Tour JF072416 & Tour RO051616 - amounts she specified to be applied to everyone did not show up correctly

**Comment by bradatkins** [comment] 2017-01-25 00:12
Duplicate of #1351, closing this one

**Closed by bradatkins** 2017-01-25 00:12 UTC
Labels: enhancement
