### ISSUE TITLE
DB | Incorrect payment amount | PA102616 (liz)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1407] opened 2016-08-16 14:06 UTC
![image](https://cloud.githubusercontent.com/assets/10079829/17701743/fbfe3370-6398-11e6-95e2-10ed7adf7f49.png)
![image](https://cloud.githubusercontent.com/assets/10079829/17701762/16d43636-6399-11e6-96d5-8f5a531b0dd7.png)

**Comment by bradatkins** [comment] 2016-09-25 13:13
Duplicate of the one I just commented on, closing

**Closed by bradatkins** 2016-09-25 13:13 UTC
Labels: For Review by 206 Tours Staff
