### ISSUE TITLE
URGENT: Account Managers assigned to tours should get orders@206tours.com via DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#324] opened 2015-04-07 18:12 UTC
Ex:  Amanda creates a tour and selects herself as the account manager of that tour.  Then every time that an email gets sent out from the DB for any passengers registered under that tour, they will get sent to clients, orders@206tours.com, and amanda@206tours.com. 

Before the whole office was getting orders@206tours.com but now it's just myself and Yaritza.  However some people still would like to receive emails from the DB and this is the best way we though of to do that. 

Does that make sense?

If you can do this urgently/ASAP we would appreciate it.

**Comment by bradatkins** [comment] 2015-04-11 00:10
What's changed? I thought everyone got orders@?

This is an enhancement though...

**Comment by ali206** [comment] 2015-04-14 14:02
Everyone was getting ALL orders@206tours.com and Milanka didn't want that to be flooding peoples emails as it's a waste of time sorting through which one's are potentially related to their specific trips.  Only Yaritza and I now receive them and disperse as necessary.

that's fine if it's an enhancement but it should be done ASAP

**Comment by bradatkins** [comment] 2015-04-14 14:10
Milkanka has the list of items logged. My guess is she will be chatting ewith everyone for their wish list type thing.

**Comment by bradatkins** [comment] 2015-09-12 13:21
Duplicate of #585

**Closed by bradatkins** 2015-09-12 13:21 UTC
Labels: enhancement
