### ISSUE TITLE
Insurance for pple not in North America

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#181] opened 2015-02-06 20:56 UTC
From: Rinda Kanidinc 
Sent: Tuesday, January 20, 2015 5:12 PM
To: Ali Boulanger; Sandra Lippold; Milanka Lachman
Subject: FW: https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417509&GENERATED=TRUE&BLUE_SHEET=Y 

Brad needs to disable pilgrims not in North America to be able to purchase insurances . 

Subject: https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417509&GENERATED=TRUE&BLUE_SHEET=Y

**Comment by bradatkins** [comment] 2015-02-07 00:28
Fixed 
![image](https://cloud.githubusercontent.com/assets/8440255/6089781/4c6b4fe2-ae36-11e4-97f8-8f464300beed.png)

**Comment by ali206** [comment] 2015-02-09 15:08
I think this has created a problem with insurance in general now as per the issue i just posted this morning.

**Comment by bradatkins** [comment] 2015-04-14 00:09
Duplicate of #229, closing this one

**Closed by bradatkins** 2015-04-14 00:09 UTC
