### ISSUE TITLE
URGENT: 422746 - Made ACH payment but i never received info

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1200] opened 2016-06-06 15:56 UTC
This is 2nd one now

![image](https://cloud.githubusercontent.com/assets/8440903/15828532/ab847352-2bdd-11e6-8acd-b3f544b5f118.png)

![image](https://cloud.githubusercontent.com/assets/8440903/15828537/b2ae4572-2bdd-11e6-816d-64841eda57d2.png)

**Comment by bradatkins** [comment] 2016-06-18 13:03
Duplicate of #1215

**Closed by bradatkins** 2016-06-18 13:03 UTC
