### ISSUE TITLE
QUICK IDEA: New Columns for Yellow Sheet: Special Request Notes, Business Class Selection, Itinerary Deviations (chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1479] opened 2016-09-14 14:48 UTC
![image](https://cloud.githubusercontent.com/assets/10079829/18516930/bbbbc098-7a68-11e6-9ff8-508a84dd9f34.png)

**Comment by bradatkins** [comment] 2017-01-28 13:37
Duplicate of some other enhancements, closing

**Closed by bradatkins** 2017-01-28 13:37 UTC
Labels: enhancement
