### ISSUE TITLE
GLITCH: Unable to select departure cities for only 1 passenger (1st instance same tour)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1528] opened 2016-09-28 14:29 UTC
I can't figure out why this can only be NY, but everyone else has access to all cities. Not urgent because it seems to be isolated and I've issued the correct ticket - but still, it could cause major problems

424552 | Edwards

![image](https://cloud.githubusercontent.com/assets/22382144/18917684/7d075d5e-8566-11e6-829c-41599b7be9fd.png)

**Comment by bradatkins** [comment] 2016-09-30 00:23
It's only NY or Chicago. What should it be?

**Comment by chris206** [comment] 2016-09-30 14:12
It should be all cities - like it is for anyone joining the tour and everyone else on the tour.
In her case - her selection is Omaha

**Comment by chris206** [comment] 2016-10-05 14:19
Hey Brad, can you please open this order up so that I can change her to the correct city? It is omaha

**Comment by bradatkins** [comment] 2016-10-06 01:19
Duplicate of #1530, closing

**Closed by bradatkins** 2016-10-06 01:19 UTC
